[versions]
android-gradle = "8.5.2"
androidx-activity-compose = "1.9.2"
androidx-core = "1.13.1"
androidx-glance = "1.1.0"
androidx-lifecycle-runtime = "2.8.5"
google-guava = "33.3.0-jre"
jetbrains-compose = "1.6.11"
jetbrains-navigation-compose = "2.7.0-alpha07"
kotlin = "2.0.20"
kotlinx-serialization = "1.7.2"
dokka = "1.9.20"
squareup-kotlinpoet = "1.18.1"
undercouch-download = "5.6.0"
vanniktech-publish = "0.29.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "androidx-glance" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "androidx-glance" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
google-guava = { group = "com.google.guava", name = "guava", version.ref = "google-guava" }
jetbrains-dokka-plugin-android = { group = "org.jetbrains.dokka", name = "android-documentation-plugin", version.ref = "dokka" }
jetbrains-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "jetbrains-navigation-compose" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
squareup-kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "squareup-kotlinpoet" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
undercouch-download = { id = "de.undercouch.download", version.ref = "undercouch-download" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }
