[versions]
android-gradle = "8.1.2"
androidx-activity-compose = "1.8.0"
androidx-core = "1.12.0"
androidx-glance = "1.0.0"
androidx-lifecycle-runtime = "2.6.2"
google-guava = "32.1.2-android"
jetbrains-compose = "1.5.3"
kotlin = "1.9.10"
squareup-kotlinpoet = "1.14.2"
undercouch-download = "5.5.0"
xmlpull = "1.1.3.1"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "androidx-glance" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
google-guava = { group = "com.google.guava", name = "guava", version.ref = "google-guava" }
jetbrains-dokka-plugin-android = { group = "org.jetbrains.dokka", name = "android-documentation-plugin", version.ref = "kotlin" }
jetbrains-dokka-plugin-versioning = { group = "org.jetbrains.dokka", name = "versioning-plugin", version.ref = "kotlin" }
squareup-kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "squareup-kotlinpoet" }
xmlpull = { group = "xmlpull", name = "xmlpull", version.ref = "xmlpull" }
xpp3 = { group = "xpp3", name = "xpp3", version = "1.1.4c" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
koltin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
undercouch-download = { id = "de.undercouch.download", version.ref = "undercouch-download" }
