[versions]
android-gradle = "8.2.2"
androidx-activity-compose = "1.8.2"
androidx-core = "1.12.0"
androidx-glance = "1.0.0"
androidx-lifecycle-runtime = "2.7.0"
google-guava = "33.0.0-android"
jetbrains-compose = "1.5.12"
kotlin = "1.9.22"
dokka = "1.9.10"
squareup-kotlinpoet = "1.16.0"
undercouch-download = "5.5.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "androidx-glance" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
google-guava = { group = "com.google.guava", name = "guava", version.ref = "google-guava" }
jetbrains-dokka-plugin-android = { group = "org.jetbrains.dokka", name = "android-documentation-plugin", version.ref = "dokka" }
squareup-kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "squareup-kotlinpoet" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
undercouch-download = { id = "de.undercouch.download", version.ref = "undercouch-download" }
