run-name: Publish tag ${{ github.ref }}
on:
  push:
    tags:
      - "v*"
permissions:
  packages: write
  contents: write
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: |
            11
            21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Cache konan directory
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts', 'buildSrc/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Remove the prefix from the version name
        run: |
          VERSION="${{ github.ref }}"
          VERSION=${VERSION#*v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build using Gradle
        run: ./gradlew assemble -x :testapp:assemble -x :dokka-vitepress-renderer:assemble -x :dokka-vitepress-renderer:multimodule:assemble

      - name: Run tests (desktop)
        run: ./gradlew desktopTest -x :testapp:desktopTest

      - name: Run tests (wasmJs)
        run: ./gradlew wasmJsTest -x :testapp:wasmJsTest

      - name: Check for API changes
        run: ./gradlew apiCheck

      - name: Generate and save dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph-exclude-projects: "^:testapp$"

      - name: Publish to GitHub Packages and Maven Central
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ github.token }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PWD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PWD }}

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          draft: true
          name: ${{ env.VERSION }}
