on:
  push:
    tags:
      - "v*"
permissions:
  packages: write
  contents: write
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 22
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Cache konan directory
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts', 'buildSrc/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Write new version
        run: |
          VERSION="${{ github.ref }}"
          VERSION=${VERSION#*v}
          sed -i "s/^VERSION_NAME\=.*$/VERSION_NAME=$VERSION/g" gradle.properties
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build using Gradle
        run: ./gradlew assemble -x :testapp:assemble

      - name: Publish to GitHub Packages and Maven Central
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ github.token }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PWD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PWD }}

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: font-symbols/build/symbols.txt
          body_path: CHANGELOG.md
          draft: true
          name: ${{ env.VERSION }}
